[package]
name = "htdb-sys"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "main"
harness = false

[dependencies]
bencher = "0.1"
bincode = "1.3"
flate2 = "1.0"
jemallocator = "0.3"
rand = "0.8"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]
